# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5
  username: tomotest
  password: tomosan0701U

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  encoding: unicode
  database: production
