class CreateMeasures < ActiveRecord::Migration[5.2]
  def change
    create_table :measures do |t|
      t.integer :user_id
      t.text :mario
      t.text :donkeykong
      t.text :link
      t.text :samus
      t.text :darksamus
      t.text :yoshi
      t.text :kirby
      t.text :fox
      t.text :pikachu
      t.text :luigi
      t.text :ness
      t.text :captainfalcon
      t.text :purin
      t.text :peach
      t.text :daisy
      t.text :koopa
      t.text :iceclimber
      t.text :sheik
      t.text :zelda
      t.text :drmario
      t.text :pichu
      t.text :falco
      t.text :marth
      t.text :lucina
      t.text :younglink
      t.text :ganondorf
      t.text :mewtwo
      t.text :roy
      t.text :chrom
      t.text :mrgame
      t.text :metaknight
      t.text :pit
      t.text :zerosuitsamus
      t.text :wario
      t.text :snake
      t.text :ike
      t.text :pokemontrainer
      t.text :diddykong
      t.text :lucas
      t.text :sonic
      t.text :dedede
      t.text :pikmin
      t.text :lucario
      t.text :robot
      t.text :toonlink
      t.text :wolf
      t.text :murabito
      t.text :rockman
      t.text :wiifittrainer
      t.text :rosetta
      t.text :littlemac
      t.text :gekkouga
      t.text :kakutou
      t.text :kenjutu
      t.text :shageki
      t.text :palutena
      t.text :pacman
      t.text :reflet
      t.text :shulk
      t.text :koopajr
      t.text :duckhunt
      t.text :ryu
      t.text :ken
      t.text :cloud
      t.text :kamui
      t.text :bayonetta
      t.text :inkling
      t.text :ridley
      t.text :simon
      t.text :richter
      t.text :kingkrool
      t.text :shizue
      t.text :gaogaen
      t.text :packunflower
      t.text :joker
      t.text :hero
      t.text :banjo
      t.text :terry
      t.text :byleth

      t.timestamps
    end
  end
end
