class ChangeMeasuresColumns < ActiveRecord::Migration[5.2]
  def change
    remove_column :measures, :mrgame, :string
    add_column :measures, :mrgame, :text
    add_column :measures, :metaknight, :text
    add_column :measures, :pit, :text
    add_column :measures, :zerosuitsamus, :text
    add_column :measures, :wario, :text
    add_column :measures, :snake, :text
    add_column :measures, :ike, :text
    add_column :measures, :pokemontrainer, :text
    add_column :measures, :diddykong, :text
    add_column :measures, :lucas, :text
    add_column :measures, :sonic, :text
    add_column :measures, :dedede, :text
    add_column :measures, :pikmin, :text
    add_column :measures, :lucario, :text
    add_column :measures, :robot, :text
    add_column :measures, :toonlink, :text
    add_column :measures, :wolf, :text
    add_column :measures, :murabito, :text
    add_column :measures, :rockman, :text
    add_column :measures, :wiifittrainer, :text
    add_column :measures, :rosetta, :text
    add_column :measures, :littlemac, :text
    add_column :measures, :gekkouga, :text
    add_column :measures, :kakutou, :text
    add_column :measures, :kenjutu, :text
    add_column :measures, :shageki, :text
    add_column :measures, :palutena, :text
    add_column :measures, :pacman, :text
    add_column :measures, :reflet, :text
    add_column :measures, :shulk, :text
    add_column :measures, :koopajr, :text
    add_column :measures, :duckhunt, :text
    add_column :measures, :ryu, :text
    add_column :measures, :ken, :text
    add_column :measures, :cloud, :text
    add_column :measures, :kamui, :text
    add_column :measures, :bayonetta, :text
    add_column :measures, :inkling, :text
    add_column :measures, :ridley, :text
    add_column :measures, :simon, :text
    add_column :measures, :richter, :text
    add_column :measures, :kingkrool, :text
    add_column :measures, :shizue, :text
    add_column :measures, :gaogaen, :text
    add_column :measures, :packunflower, :text
    add_column :measures, :joker, :text
    add_column :measures, :hero, :text
    add_column :measures, :banjo, :text
    add_column :measures, :terry, :text
    add_column :measures, :byleth, :text
    add_column :measures, :user_id, :integer
  end
end
